### ISSUE TITLE
Github Workflow Build Process

### ISSUE THREAD

**Issue by doulikecookiedough** [NCEAS/metadig-engine#470]
Currently, every time we push to the repo - `Docker Build and Publish` is executed (automated process). Discuss and determine where this should be a manual process, or if we should continue as is.

```
docker-publish:
    name: Docker Build and Publish
    if: github.ref_name == 'develop' || startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref_name, 'bugfix')
    if: github.ref_name == 'develop' || startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref_name, 'feature')
```
